server:
  port: 8000

spring:
  application:
    name:msaTesteureke

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

  cloud:
    gateway:
      # 글로벌 필터 에 관련된 내용
      default-filter:
        - name: GlobalFilter
          args:
            baseMessage: String Cloud Gateway GlobalFilter
            preLogger: true
            postLogger : true

      routes:
        - id: first-service
          url: http://localhost:8081/
          predicate:
           - Path=/first-service/**
          filters:
#            - AddRequestHeader=first-request, first-request-header2
#            - AddResponseHeader=first-response, first-response-header2
        - CustomFilter
        - id: first-service
          url: http://localhost:8081/
          predicate:
            - Path=/first-service/**
          filters:
#            - AddRequestHeader=first-request, first-request-header2
#            - AddResponseHeader=first-response, first-response-header2
            - CustomFilter
